version: '3.9'

services:
  blockmarte:
    build: .
    container_name: blockmarte
    ports:
      - "8123:80"
    restart: unless-stopped
    networks:
      - proxy-nginx

networks:
  proxy-nginx:
    external: true